#!/bin/bash
# Uninstall init — runs before application is removed
COMMON=$(dirname $0)"/common"
if [ -r "${COMMON}" ]; then . "${COMMON}"; fi
SVC_SETUP=$(dirname $0)"/service-setup"
if [ -r "${SVC_SETUP}" ]; then . "${SVC_SETUP}"; fi

uninstall_init
