#!/bin/bash
# Config init — runs before user changes environment variables
COMMON=$(dirname $0)"/common"
if [ -r "${COMMON}" ]; then . "${COMMON}"; fi
SVC_SETUP=$(dirname $0)"/service-setup"
if [ -r "${SVC_SETUP}" ]; then . "${SVC_SETUP}"; fi

config_init
